[meta]
title = "Next.js Voice Agent Starter"
description = "Get started using Deepgram's Voice Agent API with this Next.js demo app"
author = "Deepgram DX Team <devrel@deepgram.com> (https://developers.deepgram.com)"
useCase = "Agent"
language = "TypeScript"
framework = "Next.js"
sdk = "3.8.12"

[build]
command = "npm install"

[config]
sample = "sample.env"
output = ".env"

[post-build]
message = "Run `npm start` to start the web server."
